# Generated by Django 4.0.1 on 2022-02-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0006_alter_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_Authentification',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
