# Generated by Django 4.0.1 on 2022-02-15 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bibliotheque', '0007_remove_profile_city_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
